### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by VB10** [bartukaan/quake_flutter#1]
elinize sağlık

- comment kodları pushlamayın
- tema dosyanız olsun 
- iç widgetlar ıpaçralyın
- atomic widget daha çok
- static datalar için consst sınfıalrınız olsn
- service kısmınza dikkat edelim

**Comment by bartukaan** [comment]
@VB10 Veli hocam, değerli yorumların için teşekkürler...
 çok son dakikaya kaldık aceleye geldi ve zaten yetişmedi,
çok  zaman ayıramadık hata ettik
